---
- name: Install dependencies
  apt:
    name: openjdk-11-jdk
    state: present
    update_cache: yes
  become: yes

# ✅ Ensure kafka group exists before user
- name: Ensure kafka group exists
  group:
    name: "{{ kafka_group }}"
    state: present
  become: yes

- name: Ensure kafka user exists
  user:
    name: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    create_home: yes
    shell: /bin/bash
  become: yes

- name: Create install directory
  file:
    path: "{{ kafka_install_dir }}"
    state: directory
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: '0755'
  become: yes

- name: Download Kafka
  get_url:
    url: "https://archive.apache.org/dist/kafka/{{ kafka_version }}/kafka_2.13-{{ kafka_version }}.tgz"
    dest: "/tmp/kafka.tgz"
    mode: '0644'
  become: yes

- name: Extract Kafka
  unarchive:
    src: "/tmp/kafka.tgz"
    dest: "{{ kafka_install_dir }}"
    remote_src: yes
  become: yes

- name: Create log directory
  file:
    path: "{{ log_dir }}"
    state: directory
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: '0755'
  become: yes

- name: Template server.properties
  template:
    src: server.properties.j2
    dest: "{{ kafka_install_dir }}/kafka_2.13-{{ kafka_version }}/config/server.properties"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: '0644'
  become: yes

- name: Template startup script
  template:
    src: kraft-start.sh.j2
    dest: "{{ kafka_install_dir }}/kafka_2.13-{{ kafka_version }}/bin/kraft-start.sh"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: '0755'
  become: yes

- name: Create systemd unit from template
  template:
    src: kafka.service.j2
    dest: /etc/systemd/system/kafka.service
    owner: root
    group: root
    mode: '0644'
  notify: restart kafka
  become: yes

